name: 🐞 Bug report
description: File a bug report.
title: '[Bug]: '
labels:
  - bug
assignees:
  - ngocjohn
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed description 📋
      description: A detailed description of the bug
      placeholder: Describe the bug in detail, including steps to reproduce, expected behavior.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version 📦
      description: The version of the application where the bug was found
      options:
        - v1.16.1
        - v1.16.0
        - v1.15.3-beta.2
        - v1.15.2
        - v1.15.1
        - v1.14.0
        - v1.13.1
        - v1.13.0
        - v1.12.1
        - v1.12.0
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment 🌐
      description: The environment in which the bug was found (e.g., browser, OS)
      placeholder: e.g., Chrome on Windows 10
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots 📂
      description: Any relevant logs or screenshots that can help identify the issue
      placeholder: Paste logs or upload screenshots
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🛠️
