name:  ✨ Feature request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
assignees: ['ngocjohn']

body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: >
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: A detailed description of the feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Examples 🖼️
      description: Any examples or mockups to help illustrate the feature
      placeholder: "e.g., Provide a screenshot or a link to a similar feature"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context 🗒️
      description: Any other context or information you want to provide
      placeholder: "e.g., Why is this feature important to you?"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
