import {
  mdiDotsVertical,
  mdiDrag,
  mdiPencil,
  mdiPlus,
  mdiCodeBraces,
  mdiListBoxOutline,
  mdiDelete,
  mdiContentCopy,
  mdiContentCut,
  mdiClose,
  mdiChevronRight,
  mdiChevronLeft,
  mdiCodeJson,
  mdiThemeLightDark,
  mdiRestart,
  mdiChevronDown,
  mdiGrid,
  mdiEye,
} from '@mdi/js';

export const ICON = {
  CLOSE: mdiClose,
  CODE_BRACES: mdiCodeBraces,
  CONTENT_COPY: mdiContentCopy,
  CONTENT_CUT: mdiContentCut,
  DELETE: mdiDelete,
  DOTS_VERTICAL: mdiDotsVertical,
  DRAG: mdiDrag,
  LIST_BOX_OUTLINE: mdiListBoxOutline,
  PENCIL: mdiPencil,
  PLUS: mdiPlus,
  CHEVRON_RIGHT: mdiChevronRight,
  CHEVRON_LEFT: mdiChevronLeft,
  CHEVRON_DOWN: mdiChevronDown,
  CODE_JSON: mdiCodeJson,
  THEME_LIGHT_DARK: mdiThemeLightDark,
  RESTART: mdiRestart,
  GRID: mdiGrid,
  EYE: mdiEye,
};
