name: Post release
on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}

jobs:
  update-files:
    name: Update bug report template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install axios js-yaml

      - name: Update Bug Report Template
        run: node scripts/update-bug-template.js

      - name: Push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .github/ISSUE_TEMPLATE/BUG_REPORT.yml
          git commit -m "Update Bug Report Template" || echo "No changes to commit"
          git push --force origin main
